name: Build and Deploy Static Web App

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        env:
          DOTNET_NOLOGO: true #Disable welcome message
          DOTNET_CLI_TELEMETRY_OPTOUT: true #Disable telemetry logs to be collected by Microsoft
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools

      - name: Restore dependencies
        run: dotnet restore ./Client/AdventureWorks.Client.csproj

      - name: Build Blazor Project
        run: dotnet build ./Client/AdventureWorks.Client.csproj --configuration Release --no-restore

      - name: Publish Blazor Project
        run: dotnet publish ./Client/AdventureWorks.Client.csproj -c:Release --no-restore -o dist/Web --nologo

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blazor-build-artifacts
          path: dist/Web

      - name: Deploy to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: "dist/Web/wwwroot" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: true # Skip build - optional
